export const FOLLOW_ON_MANIFESTS = {
  'permanent-crew': {
    id: 'permanent-crew',
    sponsorId: 'american-compact',
    icon: 'life',
    title: 'Permanent Crew Rotation',
    proposer: 'NASA Crew Operations Office',
    threshold: 72,
    doctrine: 'Population First',
    profile: 'Founding Community',
    thesis: 'Send four permanent residents, medical capacity, and the consumables needed to turn a mission into a community.',
    allocations: [['Crew', '+4 mixed'], ['Habitat', '-25 parts'], ['Food', '+520 kg']],
    strength: 'Builds the human foundation of a permanent settlement.',
    risk: 'Ten residents immediately increase food, water, oxygen, and housing demand.',
    effects: { water: 700, oxygen: 650, food: 520, parts: 210, cargo: 4, confidence: 3 },
    crew: 4,
    cohorts: { engineering: 1, operations: 1, support: 1, residents: 1 },
    discounts: { habitat: { parts: 25, cargo: 0.8 } },
    consequence: 'The second lander carries four permanent residents. Earth now expects Ares Pathfinder to become a community, not merely a technical station.',
  },
  'machine-economy': {
    id: 'machine-economy',
    sponsorId: 'american-compact',
    icon: 'industry',
    title: 'Machine Economy',
    proposer: 'Commercial Launch Consortium',
    threshold: 68,
    doctrine: 'Manufacturing Scale',
    profile: 'Machine-Economy City',
    thesis: 'Use the earned political capital on machine tools, standardized feedstock, and two additional technical specialists.',
    allocations: [['Engineers', '+2'], ['Rover fleet', '+1'], ['Parts', '+220']],
    strength: 'Creates the strongest path toward replacing imports locally.',
    risk: 'Earth accepts a confidence penalty for backing an expensive industrial bet.',
    effects: { water: 250, oxygen: 250, food: 180, parts: 220, cargo: 6, confidence: -3 },
    crew: 2,
    cohorts: { engineering: 2 },
    rovers: 1,
    discounts: { workshop: { parts: 40, cargo: 1.2 } },
    consequence: 'The consortium won the second-window fight. Two technical specialists arrive with machine tools, feedstock, and a third cargo rover, while critics on Earth question the cost.',
  },
  'consolidation-charter': {
    id: 'consolidation-charter',
    sponsorId: 'american-compact',
    icon: 'power',
    title: 'Consolidation Charter',
    proposer: 'Congressional Mars Review Board',
    threshold: 0,
    doctrine: 'Measured Consolidation',
    profile: 'Consolidated Settlement',
    thesis: 'Hold population steady, replenish reserves, and prove the existing settlement can maintain itself before expanding again.',
    allocations: [['Reserve tanks', '-20 parts'], ['Parts', '+200'], ['Confidence', '+7%']],
    strength: 'Always authorized and provides the broadest political margin.',
    risk: 'Delays population growth and leaves Mars dependent on a cautious Earth coalition.',
    effects: { water: 450, oxygen: 450, food: 350, parts: 200, cargo: 3.2, confidence: 7 },
    crew: 0,
    discounts: { storage: { parts: 20, cargo: 0.5 } },
    consequence: 'Earth approved a cautious consolidation package. No new residents arrive, but reserves and political support recover for the next review.',
  },
  'cn-civil-cadre': {
    id: 'cn-civil-cadre',
    sponsorId: 'china-directorate',
    icon: 'life',
    title: 'Civil Settlement Cadre',
    proposer: 'National Mars Settlement Office',
    threshold: 84,
    doctrine: 'State-Planned Community',
    profile: 'State-Planned Community',
    thesis: 'Send a balanced permanent cadre with medical capacity and the reserves required to govern a civilian settlement.',
    allocations: [['Crew', '+4 mixed'], ['Habitat', '-25 parts'], ['Food', '+520 kg']],
    strength: 'Turns the technical station into a balanced permanent community.',
    risk: 'Ten residents immediately raise housing and life-support demand.',
    effects: { water: 700, oxygen: 650, food: 520, parts: 210, cargo: 4, confidence: 3 },
    crew: 4,
    cohorts: { engineering: 1, operations: 1, support: 1, residents: 1 },
    discounts: { habitat: { parts: 25, cargo: 0.8 } },
    consequence: 'The National Mars Settlement Office dispatches a permanent civil cadre. Tianwen must now prove that centralized planning can support a community as well as a mission.',
  },
  'cn-autonomous-industry': {
    id: 'cn-autonomous-industry',
    sponsorId: 'china-directorate',
    icon: 'industry',
    title: 'Autonomous Industry Bureau',
    proposer: 'State Industrial Planning Commission',
    threshold: 78,
    doctrine: 'Integrated Industrial City',
    profile: 'Integrated Industrial City',
    thesis: 'Expand machine capacity, add two technical specialists, and place another rover under the industrial bureau.',
    allocations: [['Specialists', '+2'], ['Rover fleet', '+1'], ['Parts', '+220']],
    strength: 'Builds the directorate’s strongest route toward local industrial autonomy.',
    risk: 'The costly industrial bet reduces sponsor confidence if output disappoints.',
    effects: { water: 250, oxygen: 250, food: 180, parts: 220, cargo: 6, confidence: -2 },
    crew: 2,
    cohorts: { engineering: 1, operations: 1 },
    rovers: 1,
    discounts: { workshop: { parts: 40, cargo: 1.2 } },
    consequence: 'The industrial bureau wins the second-window allocation. Two specialists, a third rover, and machine tools arrive under a demanding production schedule.',
  },
  'cn-consolidation-plan': {
    id: 'cn-consolidation-plan',
    sponsorId: 'china-directorate',
    icon: 'power',
    title: 'Five-Year Consolidation',
    proposer: 'State Council Mars Commission',
    threshold: 0,
    doctrine: 'Five-Year Consolidation',
    profile: 'Five-Year Consolidated City',
    thesis: 'Hold population steady, reinforce reserves, and reassign one engineer to surface operations before the next expansion cycle.',
    allocations: [['Operations cadre', '+1 reassigned'], ['Parts', '+210'], ['Confidence', '+6%']],
    strength: 'Always authorized and repairs the broadest operational margins.',
    risk: 'Delays population growth and concentrates more authority in the existing cadre.',
    effects: { water: 450, oxygen: 450, food: 350, parts: 210, cargo: 3.2, confidence: 6 },
    crew: 0,
    cohorts: { engineering: -1, operations: 1 },
    crossTraining: 'engineering',
    discounts: { storage: { parts: 20, cargo: 0.5 } },
    consequence: 'The commission approves a five-year consolidation plan. No new residents arrive, but reserves recover and the cadre is reorganized for surface operations.',
  },
  'eu-civic-charter': {
    id: 'eu-civic-charter',
    sponsorId: 'europe-cooperative',
    icon: 'life',
    title: 'European Civic Charter',
    proposer: 'European Mars Council',
    threshold: 80,
    doctrine: 'Multinational Civic Settlement',
    profile: 'Chartered European Community',
    thesis: 'Send four permanent residents under a common civic charter with balanced technical, medical, and administrative representation.',
    allocations: [['Crew', '+4 mixed'], ['Habitat', '-25 parts'], ['Food', '+520 kg']],
    strength: 'Creates a legitimate permanent community shared across the coalition.',
    risk: 'A larger population immediately raises housing and life-support demand.',
    effects: { water: 700, oxygen: 650, food: 520, parts: 210, cargo: 4, confidence: 4 },
    crew: 4,
    cohorts: { engineering: 1, operations: 1, support: 1, residents: 1 },
    discounts: { habitat: { parts: 25, cargo: 0.8 } },
    consequence: 'The coalition ratifies a European civic charter and dispatches four permanent residents. Kepler must now govern a community, not merely coordinate partner agencies.',
  },
  'eu-automation-union': {
    id: 'eu-automation-union',
    sponsorId: 'europe-cooperative',
    icon: 'industry',
    title: 'Automation and Industry Union',
    proposer: 'European Industrial Consortium',
    threshold: 76,
    doctrine: 'Automated Industrial Union',
    profile: 'Automated European City',
    thesis: 'Pool industrial budgets around automation, two technical specialists, and a third rover for the surface economy.',
    allocations: [['Specialists', '+2'], ['Rover fleet', '+1'], ['Parts', '+230']],
    strength: 'Turns precision manufacturing into a scalable coalition-wide industry.',
    risk: 'The expensive agreement lowers confidence among partners funding other priorities.',
    effects: { water: 300, oxygen: 300, food: 220, parts: 230, cargo: 6, confidence: -2 },
    crew: 2,
    cohorts: { engineering: 1, operations: 1 },
    rovers: 1,
    discounts: { workshop: { parts: 45, cargo: 1.3 } },
    consequence: 'The partners form an automation and industry union. Specialists, machine tools, and a third rover arrive with a strict multinational production compact.',
  },
  'eu-consensus-reserve': {
    id: 'eu-consensus-reserve',
    sponsorId: 'europe-cooperative',
    icon: 'power',
    title: 'Consensus Reserve Package',
    proposer: 'Coalition Budget Council',
    threshold: 0,
    doctrine: 'Coalition Consolidation',
    profile: 'Coalition Compact City',
    thesis: 'Defer population growth, replenish common reserves, and rebalance one engineering billet toward surface operations.',
    allocations: [['Operations billet', '+1 reassigned'], ['Parts', '+215'], ['Confidence', '+7%']],
    strength: 'Always passes and restores the coalition’s widest political and logistical margin.',
    risk: 'Delays growth and increases the administrative burden on the founding crew.',
    effects: { water: 500, oxygen: 500, food: 380, parts: 215, cargo: 3.5, confidence: 7 },
    crew: 0,
    cohorts: { engineering: -1, operations: 1 },
    crossTraining: 'engineering',
    discounts: { storage: { parts: 20, cargo: 0.5 } },
    consequence: 'The budget council passes a consensus reserve package. Kepler gains time, stores, and political margin while postponing the argument over permanent population growth.',
  },
  'ru-permanent-detachment': {
    id: 'ru-permanent-detachment',
    sponsorId: 'russia-directorate',
    icon: 'life',
    title: 'Permanent Settlement Detachment',
    proposer: 'Roscosmos Crew Directorate',
    threshold: 70,
    doctrine: 'Permanent State Settlement',
    profile: 'Permanent Russian Settlement',
    thesis: 'Send four permanent residents, medical capacity, and enough reserve to convert the expedition into a lasting community.',
    allocations: [['Crew', '+4 mixed'], ['Habitat', '-25 parts'], ['Food', '+540 kg']],
    strength: 'Builds the population and institutional depth of a permanent settlement.',
    risk: 'Ten residents strain the expedition’s already narrow housing and life-support base.',
    effects: { water: 720, oxygen: 680, food: 540, parts: 235, cargo: 4.2, confidence: 3 },
    crew: 4,
    cohorts: { engineering: 1, operations: 1, support: 1, residents: 1 },
    discounts: { habitat: { parts: 25, cargo: 0.8 } },
    consequence: 'The directorate authorizes a permanent settlement detachment. Four residents arrive, and Zvezda must now support a community under the same lean logistical system.',
  },
  'ru-heavy-industry': {
    id: 'ru-heavy-industry',
    sponsorId: 'russia-directorate',
    icon: 'industry',
    title: 'Heavy Industry Combine',
    proposer: 'State Mars Industrial Combine',
    threshold: 64,
    doctrine: 'Heavy Industrial Autonomy',
    profile: 'Heavy-Industry City',
    thesis: 'Send machine tools, two technical specialists, and another rover to build a repair economy around rugged standardized parts.',
    allocations: [['Specialists', '+2'], ['Rover fleet', '+1'], ['Parts', '+240']],
    strength: 'Creates the strongest Russian route toward local repair and industrial autonomy.',
    risk: 'Consumes political capital and deepens dependence on a single state industrial combine.',
    effects: { water: 280, oxygen: 280, food: 200, parts: 240, cargo: 6, confidence: -3 },
    crew: 2,
    cohorts: { engineering: 1, operations: 1 },
    rovers: 1,
    discounts: { workshop: { parts: 40, cargo: 1.2 } },
    consequence: 'The state industrial combine receives the second window. Specialists, a rover, and heavy machine tools arrive under a strict production mandate.',
  },
  'ru-autonomy-reserve': {
    id: 'ru-autonomy-reserve',
    sponsorId: 'russia-directorate',
    icon: 'power',
    title: 'Fortified Autonomy Reserve',
    proposer: 'Interagency Mars Commission',
    threshold: 0,
    doctrine: 'Fortified Consolidation',
    profile: 'Fortified Autonomous Outpost',
    thesis: 'Hold population steady, stockpile common spares and consumables, and harden the existing settlement before another political review.',
    allocations: [['Reserve tanks', '-20 parts'], ['Parts', '+230'], ['Confidence', '+6%']],
    strength: 'Always authorized and gives the late expedition its broadest reserve margin.',
    risk: 'Postpones growth and leaves Zvezda governed as an expeditionary outpost.',
    effects: { water: 480, oxygen: 480, food: 370, parts: 230, cargo: 3.5, confidence: 6 },
    crew: 0,
    crossTraining: 'engineering',
    discounts: { storage: { parts: 20, cargo: 0.5 } },
    consequence: 'The commission approves a fortified autonomy reserve. Zvezda gains supplies, spares, and time while postponing permanent population growth.',
  },
}

export const FOLLOW_ON_ORDER_BY_SPONSOR = {
  'american-compact': ['permanent-crew', 'machine-economy', 'consolidation-charter'],
  'china-directorate': ['cn-civil-cadre', 'cn-autonomous-industry', 'cn-consolidation-plan'],
  'europe-cooperative': ['eu-civic-charter', 'eu-automation-union', 'eu-consensus-reserve'],
  'russia-directorate': ['ru-permanent-detachment', 'ru-heavy-industry', 'ru-autonomy-reserve'],
}

export function followOnManifestsForSponsor(sponsorId) {
  return (FOLLOW_ON_ORDER_BY_SPONSOR[sponsorId] ?? []).map((id) => FOLLOW_ON_MANIFESTS[id])
}

export function followOnManifestById(id) {
  return FOLLOW_ON_MANIFESTS[id] ?? null
}
