export const MANIFESTS = {
  'baseload-first': {
    id: 'baseload-first',
    sponsorId: 'american-compact',
    icon: 'power',
    title: 'Baseload First',
    proposer: 'NASA Systems Directorate',
    doctrine: 'Assured Power',
    profile: 'Assured-Power Settlement',
    thesis: 'Use scarce launch mass on reactor hardware, shielding, and electrical spares before expanding comfort or industry.',
    allocations: [
      ['Fission unit', '-45 parts'],
      ['Parts', '+70'],
      ['Cargo', '+3.0 t'],
    ],
    strength: 'The safest route through the Sol 18 dust front.',
    risk: 'Less food and breathing-room if construction is delayed.',
    effects: { water: 200, oxygen: 240, food: 50, parts: 70, cargo: 3, confidence: 3 },
    discounts: { nuclear: { parts: 45, cargo: 1.4 } },
    consequence: 'Earth approved the reactor-first payload. Power hardware dominates the landed inventory; the crew will have to build its margin elsewhere.',
  },
  'crew-reserve': {
    id: 'crew-reserve',
    sponsorId: 'american-compact',
    icon: 'life',
    title: 'Crew Survival Reserve',
    proposer: 'Crew Medical Council',
    doctrine: 'Human Endurance',
    profile: 'Human-Endurance Settlement',
    thesis: 'Trade machinery and expansion mass for food, compressed oxygen, water bladders, and medical redundancy.',
    allocations: [
      ['Reserve tanks', '-20 parts'],
      ['Water', '+1,100 L'],
      ['Food', '+280 kg'],
    ],
    strength: 'The greatest buffer against life-support mistakes.',
    risk: 'Barely enough hardware for the required settlement core.',
    effects: { water: 1100, oxygen: 950, food: 280, parts: 40, cargo: 1, confidence: 6 },
    discounts: { storage: { parts: 20, cargo: 0.5 } },
    consequence: 'Earth approved the crew-reserve payload. Medical stores and consumables fill the holds, leaving little room for optional machinery.',
  },
  'industrial-seed': {
    id: 'industrial-seed',
    sponsorId: 'american-compact',
    icon: 'industry',
    title: 'Industrial Seed',
    proposer: 'Commercial Launch Consortium',
    doctrine: 'Local Industry',
    profile: 'Industrial-Foothold Settlement',
    thesis: 'Land machine tools, feedstock, and standardized parts so Mars can begin replacing what Earth may stop sending.',
    allocations: [
      ['Workshop', '-30 parts'],
      ['Parts', '+190'],
      ['Cargo', '+5.2 t'],
    ],
    strength: 'The strongest construction economy and expansion ceiling.',
    risk: 'Thin consumable reserves make early mistakes expensive.',
    effects: { water: 150, oxygen: 180, food: 80, parts: 190, cargo: 5.2, confidence: -3 },
    discounts: { workshop: { parts: 30, cargo: 1 } },
    consequence: 'Earth approved the industrial payload over public objections. The colony has tools and feedstock, but less emergency reserve than the crew requested.',
  },
  'cn-reactor-corridor': {
    id: 'cn-reactor-corridor',
    sponsorId: 'china-directorate',
    icon: 'power',
    title: 'Reactor Corridor',
    proposer: 'CNSA Systems Bureau',
    doctrine: 'Assured State Power',
    profile: 'Reactor-Corridor Settlement',
    thesis: 'Concentrate the first state payload on a shielded reactor corridor, switchgear, and standardized power spares.',
    allocations: [['Reactor package', '-50 parts'], ['Parts', '+90'], ['Cargo', '+3.0 t']],
    strength: 'Creates the most reliable base for uninterrupted state construction.',
    risk: 'Centralized power becomes a single demanding maintenance commitment.',
    effects: { water: 200, oxygen: 220, food: 60, parts: 90, cargo: 3, confidence: 2 },
    discounts: { nuclear: { parts: 50, cargo: 1.5 } },
    consequence: 'The commission authorized the reactor corridor. Heavy power equipment dominates the payload, giving Tianwen a firm electrical base at the cost of broader reserves.',
  },
  'cn-industrial-base': {
    id: 'cn-industrial-base',
    sponsorId: 'china-directorate',
    icon: 'industry',
    title: 'Integrated Industrial Base',
    proposer: 'State Industrial Planning Commission',
    doctrine: 'Integrated Industry',
    profile: 'Integrated Industrial Base',
    thesis: 'Land machine tools, feedstock, and interchangeable components under one centrally scheduled industrial plan.',
    allocations: [['Workshop', '-35 parts'], ['Parts', '+180'], ['Cargo', '+5.0 t']],
    strength: 'The largest early manufacturing reserve and construction ceiling.',
    risk: 'A machinery-heavy payload leaves less political and consumable margin.',
    effects: { water: 150, oxygen: 160, food: 80, parts: 180, cargo: 5, confidence: -2 },
    discounts: { workshop: { parts: 35, cargo: 1 } },
    consequence: 'The commission authorized the integrated industrial base. Tianwen receives a deep machinery reserve, but planners now expect visible returns from every landed tonne.',
  },
  'cn-life-support': {
    id: 'cn-life-support',
    sponsorId: 'china-directorate',
    icon: 'life',
    title: 'Closed-Loop Priority',
    proposer: 'CNSA Life Support Directorate',
    doctrine: 'Closed-Loop Security',
    profile: 'Closed-Loop Settlement',
    thesis: 'Spend launch mass on water, oxygen, food, and reserve storage before committing the settlement to rapid industrial growth.',
    allocations: [['Reserve tanks', '-20 parts'], ['Water', '+900 L'], ['Oxygen', '+800 kg']],
    strength: 'Provides the directorate’s strongest protection against life-support failure.',
    risk: 'Limits optional construction and delays the local machine economy.',
    effects: { water: 900, oxygen: 800, food: 220, parts: 50, cargo: 1, confidence: 4 },
    discounts: { storage: { parts: 20, cargo: 0.5 } },
    consequence: 'The commission placed closed-loop security first. Tianwen receives substantial consumable reserves, but only a narrow margin for optional machinery.',
  },
  'eu-modular-habitat': {
    id: 'eu-modular-habitat',
    sponsorId: 'europe-cooperative',
    icon: 'life',
    title: 'Modular Habitat Chain',
    proposer: 'DLR Habitat Systems Group',
    doctrine: 'Modular Human Systems',
    profile: 'Modular Habitat Network',
    thesis: 'Use common European interfaces to land expandable pressure modules, medical stores, and closed-loop reserves.',
    allocations: [['Habitat', '-25 parts'], ['Water', '+700 L'], ['Food', '+220 kg']],
    strength: 'Combines crew margin with the coalition’s best modular construction advantage.',
    risk: 'Leaves less machinery for local manufacturing and heavy power.',
    effects: { water: 700, oxygen: 600, food: 220, parts: 80, cargo: 2, confidence: 3 },
    discounts: { habitat: { parts: 25, cargo: 0.8 } },
    consequence: 'The council approves the modular habitat chain. Kepler gains a strong human-systems reserve and standardized expansion interfaces, but only modest industrial depth.',
  },
  'eu-solar-microgrid': {
    id: 'eu-solar-microgrid',
    sponsorId: 'europe-cooperative',
    icon: 'power',
    title: 'Distributed Solar Microgrid',
    proposer: 'European Energy Directorate',
    doctrine: 'Distributed Power',
    profile: 'Distributed-Energy Settlement',
    thesis: 'Disperse high-efficiency arrays and grid hardware across the site instead of concentrating the first payload on a reactor.',
    allocations: [['Solar arrays', '-15 parts'], ['Parts', '+130'], ['Cargo', '+4.0 t']],
    strength: 'Makes rapid, distributed electrical expansion unusually affordable.',
    risk: 'Four arrays are required to provide acceptable dust-front resilience.',
    effects: { water: 200, oxygen: 200, food: 80, parts: 130, cargo: 4, confidence: 2 },
    discounts: { solar: { parts: 15, cargo: 0.4 } },
    consequence: 'The council selects a distributed solar microgrid. Kepler can spread power capacity quickly, but the crew must build enough redundancy before the dust front arrives.',
  },
  'eu-precision-industry': {
    id: 'eu-precision-industry',
    sponsorId: 'europe-cooperative',
    icon: 'industry',
    title: 'Precision Manufacturing Cell',
    proposer: 'European Industrial Consortium',
    doctrine: 'Precision Industry',
    profile: 'Precision-Industry Settlement',
    thesis: 'Land compact machine tools, metrology equipment, and standardized feedstock for high-value replacement components.',
    allocations: [['Workshop', '-35 parts'], ['Parts', '+170'], ['Cargo', '+4.8 t']],
    strength: 'Creates the most cargo-efficient route to local replacement-parts production.',
    risk: 'A narrowly optimized payload carries little political or consumable reserve.',
    effects: { water: 150, oxygen: 180, food: 90, parts: 170, cargo: 4.8, confidence: -1 },
    discounts: { workshop: { parts: 35, cargo: 1.1 } },
    consequence: 'The council narrowly approves the precision manufacturing cell. Kepler gains excellent machine capability, while every coalition partner expects a share of the output.',
  },
  'ru-reactor-reserve': {
    id: 'ru-reactor-reserve',
    sponsorId: 'russia-directorate',
    icon: 'power',
    title: 'Reactor and Spares Reserve',
    proposer: 'Rosatom Surface Power Bureau',
    doctrine: 'Rugged Baseload',
    profile: 'Rugged-Reactor Settlement',
    thesis: 'Use the remaining launch mass on a simple fission unit, shielding, cable stock, and repairable electrical spares.',
    allocations: [['Reactor package', '-55 parts'], ['Parts', '+80'], ['Cargo', '+2.6 t']],
    strength: 'Provides the strongest Russian route through the dust front and later maintenance shocks.',
    risk: 'Leaves little consumable margin and no improvement to surface mobility.',
    effects: { water: 200, oxygen: 200, food: 70, parts: 80, cargo: 2.6, confidence: 2 },
    discounts: { nuclear: { parts: 55, cargo: 1.6 } },
    consequence: 'The directorate selects the reactor and spares reserve. Zvezda gains a durable power core, but almost every optional tonne has been consumed by heavy hardware.',
  },
  'ru-surface-logistics': {
    id: 'ru-surface-logistics',
    sponsorId: 'russia-directorate',
    icon: 'industry',
    title: 'Surface Logistics Train',
    proposer: 'Expedition Transport Bureau',
    doctrine: 'Mobile Surface Logistics',
    profile: 'Surface-Logistics Settlement',
    thesis: 'Land a third rugged rover, standardized wheel and motor spares, and enough cargo to keep distant worksites connected.',
    allocations: [['Rover fleet', '+1'], ['Parts', '+130'], ['Cargo', '+4.0 t']],
    strength: 'Restores construction support while preserving water haul and maintenance patrols.',
    risk: 'The vehicle-heavy payload carries the weakest political and life-support reserve.',
    effects: { water: 120, oxygen: 140, food: 60, parts: 130, cargo: 4, confidence: -2 },
    rovers: 1,
    roverAssignments: { construction: 1 },
    discounts: { ice: { parts: 15, cargo: 0.4 } },
    consequence: 'The transport bureau wins the payload dispute. A third rover lands with standardized spares, giving Zvezda a complete surface logistics train but little public margin for failure.',
  },
  'ru-expedition-reserve': {
    id: 'ru-expedition-reserve',
    sponsorId: 'russia-directorate',
    icon: 'life',
    title: 'Expedition Survival Reserve',
    proposer: 'Institute of Biomedical Problems',
    doctrine: 'Expedition Endurance',
    profile: 'Expedition-Endurance Settlement',
    thesis: 'Protect the crew with water, oxygen, preserved food, medical stores, and reserve tanks before attempting expansion.',
    allocations: [['Reserve tanks', '-20 parts'], ['Water', '+900 L'], ['Food', '+250 kg']],
    strength: 'Creates the widest human survival margin available to the late expedition.',
    risk: 'Barely funds the first construction core and leaves surface mobility unchanged.',
    effects: { water: 900, oxygen: 750, food: 250, parts: 50, cargo: 1.8, confidence: 5 },
    discounts: { storage: { parts: 20, cargo: 0.5 } },
    consequence: 'The biomedical institute secures an expedition survival reserve. Zvezda gains time and consumables, but the crew must stretch a narrow machinery allocation.',
  },
}

export const MANIFEST_ORDER_BY_SPONSOR = {
  'american-compact': ['baseload-first', 'crew-reserve', 'industrial-seed'],
  'china-directorate': ['cn-reactor-corridor', 'cn-industrial-base', 'cn-life-support'],
  'europe-cooperative': ['eu-modular-habitat', 'eu-solar-microgrid', 'eu-precision-industry'],
  'russia-directorate': ['ru-reactor-reserve', 'ru-surface-logistics', 'ru-expedition-reserve'],
}

export function manifestsForSponsor(sponsorId) {
  return (MANIFEST_ORDER_BY_SPONSOR[sponsorId] ?? []).map((id) => MANIFESTS[id])
}

export const LEGACY_MANIFEST = {
  id: 'legacy-balanced',
  sponsorId: 'american-compact',
  title: 'Pathfinder Baseline',
  doctrine: 'Balanced Pathfinder',
  profile: 'Balanced Pathfinder Settlement',
}

export function manifestById(id) {
  return MANIFESTS[id] ?? (id === LEGACY_MANIFEST.id ? LEGACY_MANIFEST : null)
}
