export const SPONSORS = {
  'american-compact': {
    id: 'american-compact',
    icon: 'commercial',
    name: 'American Public-Private Compact',
    shortName: 'American Compact',
    earthYear: 2033,
    settlementName: 'Ares Pathfinder',
    siteName: 'ARCADIA PLANITIA · SITE 03',
    transferAuthority: 'Earth-Mars Transfer Authority',
    doctrine: 'Competitive public-private coalition',
    strength: 'Earliest launch window and the greatest commercial cargo flexibility.',
    constraint: 'Sponsor confidence is exposed to shifting budgets and competing institutions.',
    resources: { water: 2200, oxygen: 1600, food: 360, parts: 220, cargo: 8.8, confidence: 70, integrity: 100 },
    crewCohorts: { engineering: 2, operations: 3, support: 1, residents: 0 },
    crossTraining: 'engineering',
    roverFleet: 2,
    roverAssignments: { water: 1, construction: 1, maintenance: 0, survey: 0 },
    intro: 'Ares Pathfinder has landed. Six crew await the coalition’s final payload authorization.',
  },
  'china-directorate': {
    id: 'china-directorate',
    icon: 'state',
    name: 'Chinese National Mars Directorate',
    shortName: 'China Directorate',
    earthYear: 2034,
    settlementName: 'Tianwen Settlement',
    siteName: 'UTOPIA PLANITIA · SITE 02',
    transferAuthority: 'State Council Mars Commission',
    doctrine: 'Central plan with dual-use industry',
    strength: 'High political confidence and a larger state-controlled hardware reserve.',
    constraint: 'Later arrival and a maintenance-first rover doctrine reduce early construction flexibility.',
    resources: { water: 2300, oxygen: 1700, food: 420, parts: 240, cargo: 9.6, confidence: 82, integrity: 100 },
    crewCohorts: { engineering: 3, operations: 2, support: 1, residents: 0 },
    crossTraining: 'operations',
    roverFleet: 2,
    roverAssignments: { water: 1, construction: 0, maintenance: 1, survey: 0 },
    intro: 'Tianwen Settlement has landed under a unified state plan. Six crew await the commission’s final cargo directive.',
  },
  'europe-cooperative': {
    id: 'europe-cooperative',
    icon: 'coalition',
    name: 'European Mars Cooperative',
    shortName: 'European Cooperative',
    earthYear: 2036,
    settlementName: 'Kepler Settlement',
    siteName: 'ELYSIUM PLANITIA · SITE 07',
    transferAuthority: 'European Mars Council',
    doctrine: 'German-led multinational engineering compact',
    strength: 'The deepest engineering cadre and the most efficient modular systems.',
    constraint: 'The latest launch window, lean cargo, and coalition votes constrain ambitious expansion.',
    resources: { water: 2150, oxygen: 1650, food: 390, parts: 250, cargo: 8, confidence: 76, integrity: 100 },
    crewCohorts: { engineering: 3, operations: 2, support: 1, residents: 0 },
    crossTraining: 'operations',
    roverFleet: 2,
    roverAssignments: { water: 0, construction: 1, maintenance: 1, survey: 0 },
    intro: 'Kepler Settlement has landed under a German-led European compact. Six crew await a unanimous first payload decision.',
  },
  'russia-directorate': {
    id: 'russia-directorate',
    icon: 'rugged',
    name: 'Russian Mars Directorate',
    shortName: 'Russian Directorate',
    earthYear: 2038,
    settlementName: 'Zvezda Settlement',
    siteName: 'ISIDIS PLANITIA · SITE 04',
    transferAuthority: 'Roscosmos Mars Directorate',
    doctrine: 'State expedition with rugged legacy systems',
    strength: 'Durable reactor engineering and maintenance-oriented surface operations.',
    constraint: 'The latest launch, lowest cargo reserve, and narrow political margin punish waste.',
    resources: { water: 2100, oxygen: 1600, food: 380, parts: 210, cargo: 7.4, confidence: 66, integrity: 100 },
    crewCohorts: { engineering: 2, operations: 3, support: 1, residents: 0 },
    crossTraining: 'engineering',
    roverFleet: 2,
    roverAssignments: { water: 1, construction: 0, maintenance: 1, survey: 0 },
    intro: 'Zvezda Settlement has landed with a lean state expedition. Six crew await the directorate’s final decision on how to spend the remaining launch mass.',
  },
}

export const SPONSOR_ORDER = ['american-compact', 'china-directorate', 'europe-cooperative', 'russia-directorate']

export function sponsorById(id) {
  return SPONSORS[id] ?? null
}
